name: guac-4h
on: workflow_dispatch

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_USER: ubuntu

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: bootstrap
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          printf '%s\n' "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
          ssh "$SSH_USER@$SERVER_IP" 'bash -s' <<'BOOT'
            sudo apt-get update -y
            sudo apt-get install -y xvfb x11vnc fluxbox google-chrome-stable
            export DISPLAY=:1
            Xvfb :1 -screen 0 1366x768x24 -ac +extension GLX +render -noreset &
            sleep 2
            x11vnc -display :1 -forever -shared -rfbport 5901 -passwd vncpass &
            fluxbox &
            google-chrome-stable --no-sandbox --disable-dev-shm-usage --display=:1 https://gemini.google.com &
            sudo systemd-run --on-active=4h --unit=auto-shutdown /sbin/shutdown -h now
            echo "✅ ready at vnc://$SERVER_IP:5901"
BOOT
