# .github/workflows/guacamole-desktop.yml

name: Temporary Guacamole Desktop via Tailscale (4-Hour Session)

on:
  workflow_dispatch:

jobs:
  guacamole-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 使用 OAuth 客户端安装并配置 Tailscale
      # 这是修改后的部分
      - name: Install Tailscale
        uses: tailscale/github-action@v2
        with:
          # 使用新的 OAuth 凭证
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          # 定义此临时节点的标签，必须与 OAuth 客户端的标签匹配
          # 并且需要提前在 Tailscale 的 ACL 策略中注册
          tags: tag:ci 
          # 主机名仍然可以自定义
          hostname: guacamole-github-runner

      # ... (后面的步骤保持不变) ...

      - name: Run Apache Guacamole with Docker
        run: |
          GUAC_USER="admin"
          GUAC_PASSWORD="${{ secrets.GUACAMOLE_PASSWORD }}"
          docker run --rm -d --name guacamole \
            -e GUACD_HOSTNAME=localhost \
            -e GUACAMOLE_ADMIN_PASSWORD="${GUAC_PASSWORD}" \
            -e GUACAMOLE_ADMIN_USER="${GUAC_USER}" \
            -p 8080:8080 \
            guacamole/guacamole
          echo "Waiting for Guacamole to become accessible..."
          sleep 30

      - name: Setup Desktop Environment (XFCE) and RDP Server
        run: |
          echo "Installing XFCE desktop and XRDP server..."
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            xfce4 \
            xrdp \
            firefox \
            dbus-x11
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp
          echo "runneruser:${{ secrets.RDP_PASSWORD }}" | sudo chpasswd
          echo "Desktop environment and RDP server are ready."

      - name: Keep workflow alive for 4 hours
        run: |
          echo "✅ Setup complete!"
          echo "You can now connect to this machine via Tailscale."
          echo "-----------------------------------------------------"
          echo "Tailscale Hostname: guacamole-github-runner"
          echo "Guacamole URL: http://guacamole-github-runner:8080/guacamole"
          # ... (省略其余 echo 信息) ...
          echo "-----------------------------------------------------"
          echo "This job will automatically stop and destroy all data in 4 hours."
          sleep 14400
