name: Build PBRP recovery.img (cannon)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v7
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y git-core gnupg ccache flex bison build-essential zip curl \
          zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev \
          x11proto-core-dev libx11-dev libreadline-dev libxml2-dev \
          libglx-mesa0 libglu1-mesa libxi6 libssl-dev bc imagemagick openjdk-11-jdk \
          repo -y
        curl -L https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod +x ~/repo && sudo mv ~/repo /usr/local/bin/repo

    - name: repo init
      run: |
        repo init -u https://github.com/PitchBlackRecoveryProject/manifest_pb \
                  -b android-14.0 --depth=1

    - name: repo sync
      run: |
        mkdir -p .repo/local_manifests
        cat > .repo/local_manifests/cannon.xml <<EOF
        <manifest>
          <project name="xiaomi-mt6853-devs/android_device_xiaomi_cannon"
                   path="device/xiaomi/cannon"
                   remote="github"
                   revision="lineage-20"
                   clone-depth="1" />
          <project name="xiaomi-mt6853-devs/android_vendor_xiaomi_cannon"
                   path="vendor/xiaomi/cannon"
                   remote="github"
                   revision="lineage-20"
                   clone-depth="1" />
        </manifest>
        EOF
        repo sync -c -j$(nproc) --no-tags --no-clone-bundle

    - name: Build PBRP
      run: |
        export USE_CCACHE=1
        ccache -M 5G
        source build/envsetup.sh
        lunch lineage_cannon-userdebug
        mka recoveryimage -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PBRP-recovery-cannon
        path: out/target/product/cannon/recovery.img
